apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: finyl-frontend
  name: finyl-frontend
  namespace: finyl
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: finyl-frontend
  template:
    metadata:
      labels:
        app: finyl-frontend
    spec:
      containers:
        - image: asia-northeast3-docker.pkg.dev/root-augury-403911/finyl-fe/finyl-frontend:latest
          imagePullPolicy: Always
          name: finyl-frontend
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 2Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
