import { Inter } from 'next/font/google'
import {Providers} from "@/app/providers";
import './globals.css'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

const inter = Inter({
    subsets: ['latin'],
    variable: "--display-font",
    display: 'swap'
})

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={inter.variable}>
            <body>
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    )
}
